# Demo

## Introduction
$$\sum_{i=1}$$
summarize part 1 in our proposal. show the formulas

## Baseline: Greedy Approach


## Hungarian Method
hospitals with capacities greater than one will be represented as multiple identical slots. For example, a hospital with a capacity of four will have four slots with the same preference cost for a given doctor. If total hospital capacity exceeds the number of doctors, dummy doctors with zero preference costs will be added as needed to create a square cost matrix. The resulting doctor-to-slot assignments will then be converted back to doctor-to-hospital assignments.

This implementation is a modified Jonker-Volgenant algorithm with no initialization, described in ref. [2].
DF Crouse. On implementing 2D rectangular assignment algorithms. IEEE Transactions on Aerospace and Electronic Systems, 52(4):1679-1696, August 2016, DOI:10.1109/TAES.2016.140952

In [ ]:
import numpy as np
cost = np.array([[4, 1, 3], [2, 0, 5], [3, 2, 2]])
from scipy.optimize import linear_sum_assignment
row_ind, col_ind = linear_sum_assignment(cost)
print(row_ind)
print(col_ind)
print(cost[row_ind, col_ind].sum())

[0 1 2]
[1 0 2]
5


In [7]:
def scipy_linear_sum_assignment(ranking, capacity):
    # ranking is a n x k matrix where n is the number of doctors and k is the total number of positions in the hospital
    # where the element at row i and column j represents the ranking of doctor i for position j (lower is better)
    # capacity is a list of length k where each element represents the number of positions available for each hospital
    n, k = ranking.shape
    # Create a cost matrix where each doctor is assigned provides to every position possible
    m = sum(capacity)  # total number of positions
    cost = np.zeros((n, m))
    for i in range(n):
        # for element j (k elements) repeat it capacity[j] times
        # concatenate all of them together
        cost_i = np.concatenate([ranking[i, j] * np.ones(capacity[j]) for j in range(k)])
        cost[i, :] = cost_i
    return linear_sum_assignment(cost)

ranking = np.array([[1, 2, 3, 4], [1, 3, 4, 2], [1, 4, 2, 3]])
capacity = [1, 1, 1, 1]  # Each hospital has one position available
row_ind, col_ind = scipy_linear_sum_assignment(ranking, capacity)
print(col_ind)

[1 0 2]


## Test Data & Comparison
ask chatgpt to generate test data for this problem (a method that takes n and k and returns random doctor preference lists and hospital preferences)
write a script to compare the two methods with the generated test data

## References
- García, A. Greedy algorithms: a review and open problems. J Inequal Appl 2025, 11 (2025). https://doi.org/10.1186/s13660-025-03254-1
- Kuhn, H.W. (1955), The Hungarian method for the assignment problem. Naval Research Logistics, 2: 83-97. https://doi.org/10.1002/nav.3800020109

## Team Contributions
- Cho - for the overview of the two methods in the proposal
- Li - for the test data generation and data validation script